apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-app
  template:
    metadata:
      labels:
        app: scraper-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9095"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: scraper-app
          image: scraper-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 9095

  