kind: Service
apiVersion: v1
metadata:
  name: scraper-service
spec:
  type: NodePort
  selector:
    app: scraper-app
  ports:
    - name: app
      nodePort: 31534
      port: 8080
      targetPort: 8080
    - name: metrics
      nodePort: 31535
      port: 9095
      targetPort: 9095