kind: Service
apiVersion: v1
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: dashboard
      nodePort: 31536
      port: 9090
      targetPort: 9090
